#include "../interface/MyObjs.h"

ClassImp(brs::MyGenParticle)
ClassImp(brs::MyRecoElectron)
ClassImp(brs::MyHLTObj)
ClassImp(brs::MyHLT)
ClassImp(brs::MyMET)
ClassImp(brs::MyGsfTrack)
ClassImp(brs::MyPFElectron)
ClassImp(brs::MyPFJet)
ClassImp(brs::MyCaloJet)
ClassImp(brs::MyEvent)
ClassImp(brs::MyMuon)
ClassImp(brs::MyPhoton)
ClassImp(brs::MySC)
ClassImp(brs::MyPU)
